import http from 'node:http';

const port = Number(process.env.PORT || 8787);

const html = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>RN JSON Inspector</title><style>
:root{color-scheme:dark;font:14px -apple-system,BlinkMacSystemFont,"SF Pro Text",Segoe UI,sans-serif;background:#101318;color:#e9edf3}*{box-sizing:border-box}body{margin:0;height:100vh;display:flex;flex-direction:column}header{height:62px;padding:0 20px;border-bottom:1px solid #2b3340;display:flex;align-items:center;gap:14px}h1{font-size:18px;margin:0}header span{color:#8c98a8;font-size:12px}.actions{margin-left:auto;display:flex;gap:8px}button{border:1px solid #3a4656;background:#202936;color:#e9edf3;border-radius:6px;padding:8px 12px;cursor:pointer}button:hover{background:#2b394b}button.primary{background:#2878d0;border-color:#4395ed}.layout{display:grid;grid-template-columns:42% 58%;min-height:0;flex:1}.input,.output{min-width:0;display:flex;flex-direction:column;padding:16px;gap:10px}.input{border-right:1px solid #2b3340}label{color:#9aa6b5;font-size:12px}textarea{flex:1;resize:none;width:100%;background:#0b0e12;border:1px solid #303a48;border-radius:7px;color:#dce6f2;padding:14px;font:13px ui-monospace,SFMono-Regular,Menlo,monospace;line-height:1.5;outline:none}textarea:focus{border-color:#3d8fe5}.bar{display:flex;align-items:center;gap:8px;min-height:36px}.bar input{flex:1;background:#171e28;border:1px solid #303a48;border-radius:6px;color:#e9edf3;padding:9px}.status{font-size:12px;color:#8e9aaa}.status.ok{color:#6bd69a}.status.bad{color:#f58d8d}.tabs{display:flex;gap:6px}.tab.active{background:#2b78cc}.pane{display:none;min-height:0;flex:1;overflow:auto}.pane.active{display:block}.tree{font:13px ui-monospace,SFMono-Regular,Menlo,monospace;line-height:1.65}.node{margin-left:18px}.key{color:#84c6ff}.string{color:#a9df9b}.number{color:#d8b7ff}.boolean{color:#ffcc80}.null{color:#9aa6b5}.toggle{cursor:pointer;color:#aeb9c8;user-select:none}.collapsed>.children{display:none}.raw{margin:0;white-space:pre-wrap;word-break:break-word;background:#0b0e12;border:1px solid #303a48;border-radius:7px;padding:14px;min-height:100%;font:13px ui-monospace,SFMono-Regular,Menlo,monospace}.hint{color:#7f8b9b;line-height:1.6}.check{display:flex;align-items:center;gap:6px;color:#aeb9c8;font-size:12px}.footer{font-size:11px;color:#697687;padding:8px 16px;border-top:1px solid #242c37}@media(max-width:850px){.layout{grid-template-columns:1fr;grid-template-rows:50% 50%}.input{border-right:0;border-bottom:1px solid #2b3340}}
</style></head><body><header><h1>RN JSON Inspector</h1><span>直接处理 Expo DevTools 的 Response 文本 · 不抓包 · 不改项目</span><div class="actions"><button id="paste">读取剪贴板</button><button id="clear">清空</button></div></header><div class="layout"><section class="input"><label for="source">把 DevTools → Response 中的内容粘贴到这里</label><textarea id="source" spellcheck="false" placeholder='{"bots": [{"id": "..."}]}'></textarea><div class="bar"><button class="primary" id="format">解析 JSON</button><label class="check"><input type="checkbox" id="redact" checked>显示时脱敏</label><span class="status" id="status">等待输入</span></div></section><section class="output"><div class="bar"><div class="tabs"><button class="tab active" data-pane="tree">Tree</button><button class="tab" data-pane="json">JSON</button><button class="tab" data-pane="raw">Raw</button></div><button id="copy" style="margin-left:auto">复制当前视图</button></div><div id="tree" class="pane active"><div class="hint">解析后显示可折叠的 JSON 树。</div></div><pre id="json" class="pane raw"></pre><pre id="raw" class="pane raw"></pre></section></div><div class="footer">数据只在本地浏览器内处理；不会上传。适用于 Expo DevTools Response 面板已能显示、但 Preview 为空的场景。</div>
<script>
const source=document.querySelector('#source'),status=document.querySelector('#status'),tree=document.querySelector('#tree'),jsonPane=document.querySelector('#json'),rawPane=document.querySelector('#raw');let parsed=null,view='tree';
const redactKeys=/token|password|secret|authorization|cookie|apikey|api_key/i;
function safe(value){if(!document.querySelector('#redact').checked)return value;if(Array.isArray(value))return value.map(safe);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[redactKeys.test(k)?'[REDACTED]':safe(v)]));return value}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function leaf(v){if(v===null)return '<span class="null">null</span>';if(typeof v==='string')return '<span class="string">&quot;'+esc(v)+'&quot;</span>';if(typeof v==='number')return '<span class="number">'+v+'</span>';if(typeof v==='boolean')return '<span class="boolean">'+v+'</span>';return ''}
function node(key,value){if(value===null||typeof value!=='object')return '<div><span class="key">'+esc(key)+':</span> '+leaf(value)+'</div>';const entries=Object.entries(value),open=Array.isArray(value)?'[':'{',close=Array.isArray(value)?']':'}';return '<div class="branch"><span class="toggle">▾ <span class="key">'+esc(key)+':</span> '+open+' <small>'+entries.length+' 项</small></span><div class="children">'+entries.map(([k,v])=>node(k,v)).join('')+'</div><span class="toggle">'+close+'</span></div>'}
function render(){if(parsed===null)return;const clean=safe(parsed);tree.innerHTML='<div class="tree">'+node('$',clean)+'</div>';jsonPane.textContent=JSON.stringify(clean,null,2);rawPane.textContent=source.value;document.querySelectorAll('.toggle').forEach(e=>e.onclick=()=>e.parentElement.classList.toggle('collapsed'));status.textContent='JSON 解析成功 · '+source.value.length.toLocaleString()+' 字符';status.className='status ok'}
document.querySelector('#format').onclick=()=>{try{parsed=JSON.parse(source.value.replace(/^\\uFEFF/,''));render()}catch(e){parsed=null;status.textContent='解析失败：'+e.message;status.className='status bad'}};
document.querySelector('#paste').onclick=async()=>{try{source.value=await navigator.clipboard.readText();document.querySelector('#format').click()}catch(e){status.textContent='无法读取剪贴板，请手动粘贴';status.className='status bad'}};
document.querySelector('#clear').onclick=()=>{source.value='';parsed=null;tree.innerHTML='<div class="hint">解析后显示可折叠的 JSON 树。</div>';jsonPane.textContent='';rawPane.textContent='';status.textContent='等待输入';status.className='status'};
document.querySelector('#redact').onchange=()=>render();document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{view=b.dataset.pane;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.pane').forEach(x=>x.classList.toggle('active',x.id===view))});document.querySelector('#copy').onclick=()=>{const el=document.querySelector('#'+view);navigator.clipboard?.writeText(el.innerText||el.textContent||'')};
</script></body></html>`;

http.createServer((req,res)=>{res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(html)}).listen(port,'127.0.0.1',()=>console.log(`RN JSON Inspector: http://127.0.0.1:${port}`));
